/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/~__root'
import { Route as SessionSessionIdImport } from './routes/~session/~$sessionId'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const SessionSessionIdIndexLazyImport = createFileRoute(
  '/session/$sessionId/',
)()
const SessionSessionIdUserIndexLazyImport = createFileRoute(
  '/session/$sessionId/user/',
)()
const SessionSessionIdRankingIndexLazyImport = createFileRoute(
  '/session/$sessionId/ranking/',
)()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/~index.lazy').then((d) => d.Route))

const SessionSessionIdRoute = SessionSessionIdImport.update({
  path: '/session/$sessionId',
  getParentRoute: () => rootRoute,
} as any)

const SessionSessionIdIndexLazyRoute = SessionSessionIdIndexLazyImport.update({
  path: '/',
  getParentRoute: () => SessionSessionIdRoute,
} as any).lazy(() =>
  import('./routes/~session/~$sessionId/~index.lazy').then((d) => d.Route),
)

const SessionSessionIdUserIndexLazyRoute =
  SessionSessionIdUserIndexLazyImport.update({
    path: '/user/',
    getParentRoute: () => SessionSessionIdRoute,
  } as any).lazy(() =>
    import('./routes/~session/~$sessionId/~user/~index.lazy').then(
      (d) => d.Route,
    ),
  )

const SessionSessionIdRankingIndexLazyRoute =
  SessionSessionIdRankingIndexLazyImport.update({
    path: '/ranking/',
    getParentRoute: () => SessionSessionIdRoute,
  } as any).lazy(() =>
    import('./routes/~session/~$sessionId/~ranking/~index.lazy').then(
      (d) => d.Route,
    ),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/session/$sessionId': {
      id: '/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/session/$sessionId'
      preLoaderRoute: typeof SessionSessionIdImport
      parentRoute: typeof rootRoute
    }
    '/session/$sessionId/': {
      id: '/session/$sessionId/'
      path: '/'
      fullPath: '/session/$sessionId/'
      preLoaderRoute: typeof SessionSessionIdIndexLazyImport
      parentRoute: typeof SessionSessionIdImport
    }
    '/session/$sessionId/ranking/': {
      id: '/session/$sessionId/ranking/'
      path: '/ranking'
      fullPath: '/session/$sessionId/ranking'
      preLoaderRoute: typeof SessionSessionIdRankingIndexLazyImport
      parentRoute: typeof SessionSessionIdImport
    }
    '/session/$sessionId/user/': {
      id: '/session/$sessionId/user/'
      path: '/user'
      fullPath: '/session/$sessionId/user'
      preLoaderRoute: typeof SessionSessionIdUserIndexLazyImport
      parentRoute: typeof SessionSessionIdImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  SessionSessionIdRoute: SessionSessionIdRoute.addChildren({
    SessionSessionIdIndexLazyRoute,
    SessionSessionIdRankingIndexLazyRoute,
    SessionSessionIdUserIndexLazyRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "~__root.tsx",
      "children": [
        "/",
        "/session/$sessionId"
      ]
    },
    "/": {
      "filePath": "~index.lazy.tsx"
    },
    "/session/$sessionId": {
      "filePath": "~session/~$sessionId.tsx",
      "children": [
        "/session/$sessionId/",
        "/session/$sessionId/ranking/",
        "/session/$sessionId/user/"
      ]
    },
    "/session/$sessionId/": {
      "filePath": "~session/~$sessionId/~index.lazy.tsx",
      "parent": "/session/$sessionId"
    },
    "/session/$sessionId/ranking/": {
      "filePath": "~session/~$sessionId/~ranking/~index.lazy.tsx",
      "parent": "/session/$sessionId"
    },
    "/session/$sessionId/user/": {
      "filePath": "~session/~$sessionId/~user/~index.lazy.tsx",
      "parent": "/session/$sessionId"
    }
  }
}
ROUTE_MANIFEST_END */
