/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/~__root'
import { Route as SessionSessionIdrootImport } from './routes/~session/~$sessionId/~__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const SessionSessionIdImport = createFileRoute('/session/$sessionId')()

// Create/Update Routes

const SessionSessionIdrootRoute = SessionSessionIdrootImport.update({
  id: '/__root',
  getParentRoute: () => SessionSessionIdRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/~index.lazy').then((d) => d.Route))

const SessionSessionIdRoute = SessionSessionIdImport.update({
  path: '/session/$sessionId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/session/$sessionId': {
      id: '/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/session/$sessionId'
      preLoaderRoute: typeof SessionSessionIdImport
      parentRoute: typeof rootRoute
    }
    '/session/$sessionId/__root': {
      id: '/session/$sessionId/__root'
      path: '/session/$sessionId'
      fullPath: '/session/$sessionId'
      preLoaderRoute: typeof SessionSessionIdrootImport
      parentRoute: typeof SessionSessionIdRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  SessionSessionIdRoute: SessionSessionIdRoute.addChildren({}),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "~__root.tsx",
      "children": [
        "/",
        "/session/$sessionId"
      ]
    },
    "/": {
      "filePath": "~index.lazy.tsx"
    },
    "/session/$sessionId": {
      "filePath": "~session/~$sessionId",
      "children": [
        "/session/$sessionId/__root"
      ]
    },
    "/session/$sessionId/__root": {
      "filePath": "~session/~$sessionId/~__root.tsx",
      "parent": "/session/$sessionId"
    }
  }
}
ROUTE_MANIFEST_END */
