/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/~__root'
import { Route as DevImport } from './routes/~dev'
import { Route as IndexImport } from './routes/~index'
import { Route as SessionSessionIdImport } from './routes/~session/~$sessionId'

// Create Virtual Routes

const SessionSessionIdUserIndexLazyImport = createFileRoute(
  '/session/$sessionId/user/',
)()
const SessionSessionIdScoreIndexLazyImport = createFileRoute(
  '/session/$sessionId/score/',
)()
const SessionSessionIdRankingIndexLazyImport = createFileRoute(
  '/session/$sessionId/ranking/',
)()
const SessionSessionIdConfigureIndexLazyImport = createFileRoute(
  '/session/$sessionId/configure/',
)()

// Create/Update Routes

const DevRoute = DevImport.update({
  path: '/dev',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SessionSessionIdRoute = SessionSessionIdImport.update({
  path: '/session/$sessionId',
  getParentRoute: () => rootRoute,
} as any)

const SessionSessionIdUserIndexLazyRoute =
  SessionSessionIdUserIndexLazyImport.update({
    path: '/user/',
    getParentRoute: () => SessionSessionIdRoute,
  } as any).lazy(() =>
    import('./routes/~session/~$sessionId/~user/~index.lazy').then(
      (d) => d.Route,
    ),
  )

const SessionSessionIdScoreIndexLazyRoute =
  SessionSessionIdScoreIndexLazyImport.update({
    path: '/score/',
    getParentRoute: () => SessionSessionIdRoute,
  } as any).lazy(() =>
    import('./routes/~session/~$sessionId/~score/~index.lazy').then(
      (d) => d.Route,
    ),
  )

const SessionSessionIdRankingIndexLazyRoute =
  SessionSessionIdRankingIndexLazyImport.update({
    path: '/ranking/',
    getParentRoute: () => SessionSessionIdRoute,
  } as any).lazy(() =>
    import('./routes/~session/~$sessionId/~ranking/~index.lazy').then(
      (d) => d.Route,
    ),
  )

const SessionSessionIdConfigureIndexLazyRoute =
  SessionSessionIdConfigureIndexLazyImport.update({
    path: '/configure/',
    getParentRoute: () => SessionSessionIdRoute,
  } as any).lazy(() =>
    import('./routes/~session/~$sessionId/~configure/~index.lazy').then(
      (d) => d.Route,
    ),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevImport
      parentRoute: typeof rootRoute
    }
    '/session/$sessionId': {
      id: '/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/session/$sessionId'
      preLoaderRoute: typeof SessionSessionIdImport
      parentRoute: typeof rootRoute
    }
    '/session/$sessionId/configure/': {
      id: '/session/$sessionId/configure/'
      path: '/configure'
      fullPath: '/session/$sessionId/configure'
      preLoaderRoute: typeof SessionSessionIdConfigureIndexLazyImport
      parentRoute: typeof SessionSessionIdImport
    }
    '/session/$sessionId/ranking/': {
      id: '/session/$sessionId/ranking/'
      path: '/ranking'
      fullPath: '/session/$sessionId/ranking'
      preLoaderRoute: typeof SessionSessionIdRankingIndexLazyImport
      parentRoute: typeof SessionSessionIdImport
    }
    '/session/$sessionId/score/': {
      id: '/session/$sessionId/score/'
      path: '/score'
      fullPath: '/session/$sessionId/score'
      preLoaderRoute: typeof SessionSessionIdScoreIndexLazyImport
      parentRoute: typeof SessionSessionIdImport
    }
    '/session/$sessionId/user/': {
      id: '/session/$sessionId/user/'
      path: '/user'
      fullPath: '/session/$sessionId/user'
      preLoaderRoute: typeof SessionSessionIdUserIndexLazyImport
      parentRoute: typeof SessionSessionIdImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  DevRoute,
  SessionSessionIdRoute: SessionSessionIdRoute.addChildren({
    SessionSessionIdConfigureIndexLazyRoute,
    SessionSessionIdRankingIndexLazyRoute,
    SessionSessionIdScoreIndexLazyRoute,
    SessionSessionIdUserIndexLazyRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "~__root.tsx",
      "children": [
        "/",
        "/dev",
        "/session/$sessionId"
      ]
    },
    "/": {
      "filePath": "~index.tsx"
    },
    "/dev": {
      "filePath": "~dev.tsx"
    },
    "/session/$sessionId": {
      "filePath": "~session/~$sessionId.tsx",
      "children": [
        "/session/$sessionId/configure/",
        "/session/$sessionId/ranking/",
        "/session/$sessionId/score/",
        "/session/$sessionId/user/"
      ]
    },
    "/session/$sessionId/configure/": {
      "filePath": "~session/~$sessionId/~configure/~index.lazy.tsx",
      "parent": "/session/$sessionId"
    },
    "/session/$sessionId/ranking/": {
      "filePath": "~session/~$sessionId/~ranking/~index.lazy.tsx",
      "parent": "/session/$sessionId"
    },
    "/session/$sessionId/score/": {
      "filePath": "~session/~$sessionId/~score/~index.lazy.tsx",
      "parent": "/session/$sessionId"
    },
    "/session/$sessionId/user/": {
      "filePath": "~session/~$sessionId/~user/~index.lazy.tsx",
      "parent": "/session/$sessionId"
    }
  }
}
ROUTE_MANIFEST_END */
