/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/~__root'
import { Route as DevImport } from './routes/~dev'
import { Route as IndexImport } from './routes/~index'
import { Route as SessionDocumentIdImport } from './routes/~session/~$documentId'

// Create Virtual Routes

const SessionDocumentIdUserIndexLazyImport = createFileRoute(
  '/session/$documentId/user/',
)()
const SessionDocumentIdScoreIndexLazyImport = createFileRoute(
  '/session/$documentId/score/',
)()
const SessionDocumentIdRankingIndexLazyImport = createFileRoute(
  '/session/$documentId/ranking/',
)()
const SessionDocumentIdConfigureIndexLazyImport = createFileRoute(
  '/session/$documentId/configure/',
)()

// Create/Update Routes

const DevRoute = DevImport.update({
  path: '/dev',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SessionDocumentIdRoute = SessionDocumentIdImport.update({
  path: '/session/$documentId',
  getParentRoute: () => rootRoute,
} as any)

const SessionDocumentIdUserIndexLazyRoute =
  SessionDocumentIdUserIndexLazyImport.update({
    path: '/user/',
    getParentRoute: () => SessionDocumentIdRoute,
  } as any).lazy(() =>
    import('./routes/~session/~$documentId/~user/~index.lazy').then(
      (d) => d.Route,
    ),
  )

const SessionDocumentIdScoreIndexLazyRoute =
  SessionDocumentIdScoreIndexLazyImport.update({
    path: '/score/',
    getParentRoute: () => SessionDocumentIdRoute,
  } as any).lazy(() =>
    import('./routes/~session/~$documentId/~score/~index.lazy').then(
      (d) => d.Route,
    ),
  )

const SessionDocumentIdRankingIndexLazyRoute =
  SessionDocumentIdRankingIndexLazyImport.update({
    path: '/ranking/',
    getParentRoute: () => SessionDocumentIdRoute,
  } as any).lazy(() =>
    import('./routes/~session/~$documentId/~ranking/~index.lazy').then(
      (d) => d.Route,
    ),
  )

const SessionDocumentIdConfigureIndexLazyRoute =
  SessionDocumentIdConfigureIndexLazyImport.update({
    path: '/configure/',
    getParentRoute: () => SessionDocumentIdRoute,
  } as any).lazy(() =>
    import('./routes/~session/~$documentId/~configure/~index.lazy').then(
      (d) => d.Route,
    ),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevImport
      parentRoute: typeof rootRoute
    }
    '/session/$documentId': {
      id: '/session/$documentId'
      path: '/session/$documentId'
      fullPath: '/session/$documentId'
      preLoaderRoute: typeof SessionDocumentIdImport
      parentRoute: typeof rootRoute
    }
    '/session/$documentId/configure/': {
      id: '/session/$documentId/configure/'
      path: '/configure'
      fullPath: '/session/$documentId/configure'
      preLoaderRoute: typeof SessionDocumentIdConfigureIndexLazyImport
      parentRoute: typeof SessionDocumentIdImport
    }
    '/session/$documentId/ranking/': {
      id: '/session/$documentId/ranking/'
      path: '/ranking'
      fullPath: '/session/$documentId/ranking'
      preLoaderRoute: typeof SessionDocumentIdRankingIndexLazyImport
      parentRoute: typeof SessionDocumentIdImport
    }
    '/session/$documentId/score/': {
      id: '/session/$documentId/score/'
      path: '/score'
      fullPath: '/session/$documentId/score'
      preLoaderRoute: typeof SessionDocumentIdScoreIndexLazyImport
      parentRoute: typeof SessionDocumentIdImport
    }
    '/session/$documentId/user/': {
      id: '/session/$documentId/user/'
      path: '/user'
      fullPath: '/session/$documentId/user'
      preLoaderRoute: typeof SessionDocumentIdUserIndexLazyImport
      parentRoute: typeof SessionDocumentIdImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  DevRoute,
  SessionDocumentIdRoute: SessionDocumentIdRoute.addChildren({
    SessionDocumentIdConfigureIndexLazyRoute,
    SessionDocumentIdRankingIndexLazyRoute,
    SessionDocumentIdScoreIndexLazyRoute,
    SessionDocumentIdUserIndexLazyRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "~__root.tsx",
      "children": [
        "/",
        "/dev",
        "/session/$documentId"
      ]
    },
    "/": {
      "filePath": "~index.tsx"
    },
    "/dev": {
      "filePath": "~dev.tsx"
    },
    "/session/$documentId": {
      "filePath": "~session/~$documentId.tsx",
      "children": [
        "/session/$documentId/configure/",
        "/session/$documentId/ranking/",
        "/session/$documentId/score/",
        "/session/$documentId/user/"
      ]
    },
    "/session/$documentId/configure/": {
      "filePath": "~session/~$documentId/~configure/~index.lazy.tsx",
      "parent": "/session/$documentId"
    },
    "/session/$documentId/ranking/": {
      "filePath": "~session/~$documentId/~ranking/~index.lazy.tsx",
      "parent": "/session/$documentId"
    },
    "/session/$documentId/score/": {
      "filePath": "~session/~$documentId/~score/~index.lazy.tsx",
      "parent": "/session/$documentId"
    },
    "/session/$documentId/user/": {
      "filePath": "~session/~$documentId/~user/~index.lazy.tsx",
      "parent": "/session/$documentId"
    }
  }
}
ROUTE_MANIFEST_END */
