/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* biome-ignore-all lint: auto-generated */

/// <reference types="vite/client" />
interface ImportMetaEnv {
  readonly VITE_REALTIME_ENDPOINT: string
  readonly VITE_REALTIME_TOPIC_PREFIX: string
  readonly VITE_REALTIME_AUTHORIZER: string
}
interface ImportMeta {
  readonly env: ImportMetaEnv
}